################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO.c \
D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_AntialiasedText.c \
D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_Automotive.c \
D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_BarGraph.c \
D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_Bitmap.c \
D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_ColorBar.c \
D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_Conf.c \
D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_Cursor.c \
D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_Fading.c \
D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_Graph.c \
D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_IconView.c \
D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_ImageFlow.c \
D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_Intro.c \
D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_Listview.c \
D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_RadialMenu.c \
D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_Resource.c \
D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_Skinning.c \
D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_Speed.c \
D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_Speedometer.c \
D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_TransparentDialog.c \
D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_Treeview.c \
D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_VScreen.c \
D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_WashingMachine.c \
D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_ZoomAndRotate.c 

OBJS += \
./components/cpn_gui/demo/GUIDEMO.o \
./components/cpn_gui/demo/GUIDEMO_AntialiasedText.o \
./components/cpn_gui/demo/GUIDEMO_Automotive.o \
./components/cpn_gui/demo/GUIDEMO_BarGraph.o \
./components/cpn_gui/demo/GUIDEMO_Bitmap.o \
./components/cpn_gui/demo/GUIDEMO_ColorBar.o \
./components/cpn_gui/demo/GUIDEMO_Conf.o \
./components/cpn_gui/demo/GUIDEMO_Cursor.o \
./components/cpn_gui/demo/GUIDEMO_Fading.o \
./components/cpn_gui/demo/GUIDEMO_Graph.o \
./components/cpn_gui/demo/GUIDEMO_IconView.o \
./components/cpn_gui/demo/GUIDEMO_ImageFlow.o \
./components/cpn_gui/demo/GUIDEMO_Intro.o \
./components/cpn_gui/demo/GUIDEMO_Listview.o \
./components/cpn_gui/demo/GUIDEMO_RadialMenu.o \
./components/cpn_gui/demo/GUIDEMO_Resource.o \
./components/cpn_gui/demo/GUIDEMO_Skinning.o \
./components/cpn_gui/demo/GUIDEMO_Speed.o \
./components/cpn_gui/demo/GUIDEMO_Speedometer.o \
./components/cpn_gui/demo/GUIDEMO_TransparentDialog.o \
./components/cpn_gui/demo/GUIDEMO_Treeview.o \
./components/cpn_gui/demo/GUIDEMO_VScreen.o \
./components/cpn_gui/demo/GUIDEMO_WashingMachine.o \
./components/cpn_gui/demo/GUIDEMO_ZoomAndRotate.o 

C_DEPS += \
./components/cpn_gui/demo/GUIDEMO.d \
./components/cpn_gui/demo/GUIDEMO_AntialiasedText.d \
./components/cpn_gui/demo/GUIDEMO_Automotive.d \
./components/cpn_gui/demo/GUIDEMO_BarGraph.d \
./components/cpn_gui/demo/GUIDEMO_Bitmap.d \
./components/cpn_gui/demo/GUIDEMO_ColorBar.d \
./components/cpn_gui/demo/GUIDEMO_Conf.d \
./components/cpn_gui/demo/GUIDEMO_Cursor.d \
./components/cpn_gui/demo/GUIDEMO_Fading.d \
./components/cpn_gui/demo/GUIDEMO_Graph.d \
./components/cpn_gui/demo/GUIDEMO_IconView.d \
./components/cpn_gui/demo/GUIDEMO_ImageFlow.d \
./components/cpn_gui/demo/GUIDEMO_Intro.d \
./components/cpn_gui/demo/GUIDEMO_Listview.d \
./components/cpn_gui/demo/GUIDEMO_RadialMenu.d \
./components/cpn_gui/demo/GUIDEMO_Resource.d \
./components/cpn_gui/demo/GUIDEMO_Skinning.d \
./components/cpn_gui/demo/GUIDEMO_Speed.d \
./components/cpn_gui/demo/GUIDEMO_Speedometer.d \
./components/cpn_gui/demo/GUIDEMO_TransparentDialog.d \
./components/cpn_gui/demo/GUIDEMO_Treeview.d \
./components/cpn_gui/demo/GUIDEMO_VScreen.d \
./components/cpn_gui/demo/GUIDEMO_WashingMachine.d \
./components/cpn_gui/demo/GUIDEMO_ZoomAndRotate.d 


# Each subdirectory must supply rules for building sources it contributes
components/cpn_gui/demo/GUIDEMO.o: D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO.c
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Windows GCC C Compiler (Sourcery Lite Bare)'
	arm-none-eabi-gcc -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\applications" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\configures" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_fatfs" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_tone" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\demo" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\config" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\driver" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\apps" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\tcpip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\uip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\chips" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_lib" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\ezos" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_sdcard" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_spiflash" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\STM32F10x_StdPeriph_Driver\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\DeviceSupport\ST\STM32F10x" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\CoreSupport" -Os -ffunction-sections -fdata-sections -Wall -Wa,-adhlns="$@.lst" -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -mcpu=cortex-m3 -mthumb -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

components/cpn_gui/demo/GUIDEMO_AntialiasedText.o: D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_AntialiasedText.c
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Windows GCC C Compiler (Sourcery Lite Bare)'
	arm-none-eabi-gcc -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\applications" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\configures" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_fatfs" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_tone" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\demo" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\config" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\driver" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\apps" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\tcpip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\uip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\chips" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_lib" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\ezos" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_sdcard" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_spiflash" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\STM32F10x_StdPeriph_Driver\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\DeviceSupport\ST\STM32F10x" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\CoreSupport" -Os -ffunction-sections -fdata-sections -Wall -Wa,-adhlns="$@.lst" -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -mcpu=cortex-m3 -mthumb -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

components/cpn_gui/demo/GUIDEMO_Automotive.o: D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_Automotive.c
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Windows GCC C Compiler (Sourcery Lite Bare)'
	arm-none-eabi-gcc -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\applications" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\configures" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_fatfs" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_tone" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\demo" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\config" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\driver" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\apps" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\tcpip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\uip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\chips" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_lib" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\ezos" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_sdcard" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_spiflash" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\STM32F10x_StdPeriph_Driver\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\DeviceSupport\ST\STM32F10x" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\CoreSupport" -Os -ffunction-sections -fdata-sections -Wall -Wa,-adhlns="$@.lst" -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -mcpu=cortex-m3 -mthumb -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

components/cpn_gui/demo/GUIDEMO_BarGraph.o: D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_BarGraph.c
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Windows GCC C Compiler (Sourcery Lite Bare)'
	arm-none-eabi-gcc -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\applications" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\configures" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_fatfs" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_tone" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\demo" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\config" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\driver" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\apps" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\tcpip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\uip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\chips" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_lib" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\ezos" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_sdcard" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_spiflash" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\STM32F10x_StdPeriph_Driver\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\DeviceSupport\ST\STM32F10x" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\CoreSupport" -Os -ffunction-sections -fdata-sections -Wall -Wa,-adhlns="$@.lst" -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -mcpu=cortex-m3 -mthumb -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

components/cpn_gui/demo/GUIDEMO_Bitmap.o: D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_Bitmap.c
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Windows GCC C Compiler (Sourcery Lite Bare)'
	arm-none-eabi-gcc -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\applications" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\configures" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_fatfs" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_tone" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\demo" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\config" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\driver" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\apps" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\tcpip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\uip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\chips" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_lib" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\ezos" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_sdcard" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_spiflash" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\STM32F10x_StdPeriph_Driver\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\DeviceSupport\ST\STM32F10x" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\CoreSupport" -Os -ffunction-sections -fdata-sections -Wall -Wa,-adhlns="$@.lst" -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -mcpu=cortex-m3 -mthumb -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

components/cpn_gui/demo/GUIDEMO_ColorBar.o: D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_ColorBar.c
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Windows GCC C Compiler (Sourcery Lite Bare)'
	arm-none-eabi-gcc -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\applications" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\configures" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_fatfs" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_tone" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\demo" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\config" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\driver" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\apps" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\tcpip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\uip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\chips" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_lib" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\ezos" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_sdcard" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_spiflash" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\STM32F10x_StdPeriph_Driver\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\DeviceSupport\ST\STM32F10x" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\CoreSupport" -Os -ffunction-sections -fdata-sections -Wall -Wa,-adhlns="$@.lst" -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -mcpu=cortex-m3 -mthumb -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

components/cpn_gui/demo/GUIDEMO_Conf.o: D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_Conf.c
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Windows GCC C Compiler (Sourcery Lite Bare)'
	arm-none-eabi-gcc -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\applications" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\configures" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_fatfs" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_tone" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\demo" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\config" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\driver" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\apps" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\tcpip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\uip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\chips" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_lib" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\ezos" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_sdcard" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_spiflash" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\STM32F10x_StdPeriph_Driver\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\DeviceSupport\ST\STM32F10x" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\CoreSupport" -Os -ffunction-sections -fdata-sections -Wall -Wa,-adhlns="$@.lst" -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -mcpu=cortex-m3 -mthumb -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

components/cpn_gui/demo/GUIDEMO_Cursor.o: D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_Cursor.c
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Windows GCC C Compiler (Sourcery Lite Bare)'
	arm-none-eabi-gcc -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\applications" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\configures" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_fatfs" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_tone" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\demo" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\config" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\driver" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\apps" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\tcpip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\uip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\chips" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_lib" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\ezos" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_sdcard" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_spiflash" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\STM32F10x_StdPeriph_Driver\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\DeviceSupport\ST\STM32F10x" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\CoreSupport" -Os -ffunction-sections -fdata-sections -Wall -Wa,-adhlns="$@.lst" -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -mcpu=cortex-m3 -mthumb -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

components/cpn_gui/demo/GUIDEMO_Fading.o: D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_Fading.c
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Windows GCC C Compiler (Sourcery Lite Bare)'
	arm-none-eabi-gcc -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\applications" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\configures" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_fatfs" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_tone" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\demo" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\config" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\driver" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\apps" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\tcpip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\uip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\chips" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_lib" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\ezos" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_sdcard" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_spiflash" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\STM32F10x_StdPeriph_Driver\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\DeviceSupport\ST\STM32F10x" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\CoreSupport" -Os -ffunction-sections -fdata-sections -Wall -Wa,-adhlns="$@.lst" -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -mcpu=cortex-m3 -mthumb -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

components/cpn_gui/demo/GUIDEMO_Graph.o: D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_Graph.c
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Windows GCC C Compiler (Sourcery Lite Bare)'
	arm-none-eabi-gcc -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\applications" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\configures" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_fatfs" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_tone" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\demo" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\config" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\driver" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\apps" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\tcpip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\uip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\chips" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_lib" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\ezos" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_sdcard" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_spiflash" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\STM32F10x_StdPeriph_Driver\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\DeviceSupport\ST\STM32F10x" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\CoreSupport" -Os -ffunction-sections -fdata-sections -Wall -Wa,-adhlns="$@.lst" -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -mcpu=cortex-m3 -mthumb -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

components/cpn_gui/demo/GUIDEMO_IconView.o: D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_IconView.c
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Windows GCC C Compiler (Sourcery Lite Bare)'
	arm-none-eabi-gcc -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\applications" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\configures" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_fatfs" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_tone" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\demo" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\config" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\driver" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\apps" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\tcpip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\uip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\chips" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_lib" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\ezos" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_sdcard" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_spiflash" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\STM32F10x_StdPeriph_Driver\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\DeviceSupport\ST\STM32F10x" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\CoreSupport" -Os -ffunction-sections -fdata-sections -Wall -Wa,-adhlns="$@.lst" -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -mcpu=cortex-m3 -mthumb -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

components/cpn_gui/demo/GUIDEMO_ImageFlow.o: D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_ImageFlow.c
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Windows GCC C Compiler (Sourcery Lite Bare)'
	arm-none-eabi-gcc -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\applications" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\configures" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_fatfs" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_tone" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\demo" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\config" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\driver" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\apps" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\tcpip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\uip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\chips" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_lib" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\ezos" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_sdcard" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_spiflash" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\STM32F10x_StdPeriph_Driver\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\DeviceSupport\ST\STM32F10x" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\CoreSupport" -Os -ffunction-sections -fdata-sections -Wall -Wa,-adhlns="$@.lst" -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -mcpu=cortex-m3 -mthumb -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

components/cpn_gui/demo/GUIDEMO_Intro.o: D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_Intro.c
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Windows GCC C Compiler (Sourcery Lite Bare)'
	arm-none-eabi-gcc -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\applications" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\configures" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_fatfs" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_tone" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\demo" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\config" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\driver" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\apps" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\tcpip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\uip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\chips" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_lib" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\ezos" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_sdcard" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_spiflash" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\STM32F10x_StdPeriph_Driver\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\DeviceSupport\ST\STM32F10x" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\CoreSupport" -Os -ffunction-sections -fdata-sections -Wall -Wa,-adhlns="$@.lst" -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -mcpu=cortex-m3 -mthumb -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

components/cpn_gui/demo/GUIDEMO_Listview.o: D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_Listview.c
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Windows GCC C Compiler (Sourcery Lite Bare)'
	arm-none-eabi-gcc -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\applications" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\configures" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_fatfs" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_tone" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\demo" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\config" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\driver" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\apps" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\tcpip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\uip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\chips" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_lib" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\ezos" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_sdcard" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_spiflash" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\STM32F10x_StdPeriph_Driver\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\DeviceSupport\ST\STM32F10x" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\CoreSupport" -Os -ffunction-sections -fdata-sections -Wall -Wa,-adhlns="$@.lst" -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -mcpu=cortex-m3 -mthumb -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

components/cpn_gui/demo/GUIDEMO_RadialMenu.o: D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_RadialMenu.c
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Windows GCC C Compiler (Sourcery Lite Bare)'
	arm-none-eabi-gcc -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\applications" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\configures" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_fatfs" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_tone" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\demo" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\config" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\driver" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\apps" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\tcpip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\uip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\chips" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_lib" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\ezos" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_sdcard" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_spiflash" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\STM32F10x_StdPeriph_Driver\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\DeviceSupport\ST\STM32F10x" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\CoreSupport" -Os -ffunction-sections -fdata-sections -Wall -Wa,-adhlns="$@.lst" -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -mcpu=cortex-m3 -mthumb -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

components/cpn_gui/demo/GUIDEMO_Resource.o: D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_Resource.c
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Windows GCC C Compiler (Sourcery Lite Bare)'
	arm-none-eabi-gcc -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\applications" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\configures" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_fatfs" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_tone" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\demo" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\config" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\driver" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\apps" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\tcpip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\uip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\chips" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_lib" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\ezos" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_sdcard" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_spiflash" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\STM32F10x_StdPeriph_Driver\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\DeviceSupport\ST\STM32F10x" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\CoreSupport" -Os -ffunction-sections -fdata-sections -Wall -Wa,-adhlns="$@.lst" -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -mcpu=cortex-m3 -mthumb -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

components/cpn_gui/demo/GUIDEMO_Skinning.o: D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_Skinning.c
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Windows GCC C Compiler (Sourcery Lite Bare)'
	arm-none-eabi-gcc -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\applications" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\configures" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_fatfs" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_tone" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\demo" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\config" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\driver" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\apps" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\tcpip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\uip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\chips" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_lib" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\ezos" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_sdcard" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_spiflash" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\STM32F10x_StdPeriph_Driver\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\DeviceSupport\ST\STM32F10x" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\CoreSupport" -Os -ffunction-sections -fdata-sections -Wall -Wa,-adhlns="$@.lst" -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -mcpu=cortex-m3 -mthumb -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

components/cpn_gui/demo/GUIDEMO_Speed.o: D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_Speed.c
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Windows GCC C Compiler (Sourcery Lite Bare)'
	arm-none-eabi-gcc -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\applications" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\configures" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_fatfs" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_tone" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\demo" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\config" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\driver" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\apps" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\tcpip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\uip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\chips" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_lib" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\ezos" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_sdcard" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_spiflash" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\STM32F10x_StdPeriph_Driver\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\DeviceSupport\ST\STM32F10x" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\CoreSupport" -Os -ffunction-sections -fdata-sections -Wall -Wa,-adhlns="$@.lst" -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -mcpu=cortex-m3 -mthumb -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

components/cpn_gui/demo/GUIDEMO_Speedometer.o: D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_Speedometer.c
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Windows GCC C Compiler (Sourcery Lite Bare)'
	arm-none-eabi-gcc -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\applications" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\configures" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_fatfs" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_tone" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\demo" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\config" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\driver" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\apps" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\tcpip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\uip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\chips" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_lib" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\ezos" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_sdcard" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_spiflash" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\STM32F10x_StdPeriph_Driver\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\DeviceSupport\ST\STM32F10x" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\CoreSupport" -Os -ffunction-sections -fdata-sections -Wall -Wa,-adhlns="$@.lst" -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -mcpu=cortex-m3 -mthumb -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

components/cpn_gui/demo/GUIDEMO_TransparentDialog.o: D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_TransparentDialog.c
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Windows GCC C Compiler (Sourcery Lite Bare)'
	arm-none-eabi-gcc -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\applications" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\configures" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_fatfs" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_tone" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\demo" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\config" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\driver" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\apps" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\tcpip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\uip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\chips" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_lib" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\ezos" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_sdcard" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_spiflash" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\STM32F10x_StdPeriph_Driver\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\DeviceSupport\ST\STM32F10x" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\CoreSupport" -Os -ffunction-sections -fdata-sections -Wall -Wa,-adhlns="$@.lst" -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -mcpu=cortex-m3 -mthumb -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

components/cpn_gui/demo/GUIDEMO_Treeview.o: D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_Treeview.c
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Windows GCC C Compiler (Sourcery Lite Bare)'
	arm-none-eabi-gcc -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\applications" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\configures" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_fatfs" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_tone" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\demo" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\config" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\driver" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\apps" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\tcpip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\uip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\chips" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_lib" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\ezos" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_sdcard" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_spiflash" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\STM32F10x_StdPeriph_Driver\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\DeviceSupport\ST\STM32F10x" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\CoreSupport" -Os -ffunction-sections -fdata-sections -Wall -Wa,-adhlns="$@.lst" -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -mcpu=cortex-m3 -mthumb -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

components/cpn_gui/demo/GUIDEMO_VScreen.o: D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_VScreen.c
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Windows GCC C Compiler (Sourcery Lite Bare)'
	arm-none-eabi-gcc -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\applications" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\configures" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_fatfs" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_tone" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\demo" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\config" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\driver" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\apps" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\tcpip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\uip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\chips" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_lib" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\ezos" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_sdcard" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_spiflash" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\STM32F10x_StdPeriph_Driver\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\DeviceSupport\ST\STM32F10x" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\CoreSupport" -Os -ffunction-sections -fdata-sections -Wall -Wa,-adhlns="$@.lst" -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -mcpu=cortex-m3 -mthumb -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

components/cpn_gui/demo/GUIDEMO_WashingMachine.o: D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_WashingMachine.c
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Windows GCC C Compiler (Sourcery Lite Bare)'
	arm-none-eabi-gcc -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\applications" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\configures" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_fatfs" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_tone" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\demo" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\config" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\driver" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\apps" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\tcpip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\uip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\chips" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_lib" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\ezos" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_sdcard" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_spiflash" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\STM32F10x_StdPeriph_Driver\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\DeviceSupport\ST\STM32F10x" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\CoreSupport" -Os -ffunction-sections -fdata-sections -Wall -Wa,-adhlns="$@.lst" -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -mcpu=cortex-m3 -mthumb -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

components/cpn_gui/demo/GUIDEMO_ZoomAndRotate.o: D:/Users/draapho/Desktop/stm32_ezos_v231/components/cpn_gui/demo/GUIDEMO_ZoomAndRotate.c
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Windows GCC C Compiler (Sourcery Lite Bare)'
	arm-none-eabi-gcc -DUSE_STDPERIPH_DRIVER -DSTM32F10X_CL -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\applications" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\bsp\gold_bull\configures" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_fatfs" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_tone" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\demo" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\config" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_gui\driver" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\apps" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\tcpip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\uip" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_uip\chips" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components\cpn_lib" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\components" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\ezos" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_sdcard" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\drv_spiflash" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\STM32F10x_StdPeriph_Driver\inc" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\DeviceSupport\ST\STM32F10x" -I"D:\Users\draapho\Desktop\stm32_ezos_v231\drivers\libraries\CMSIS\CM3\CoreSupport" -Os -ffunction-sections -fdata-sections -Wall -Wa,-adhlns="$@.lst" -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -mcpu=cortex-m3 -mthumb -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


